"""Initial migration

Revision ID: b2c71bd9c34e
Revises: 
Create Date: 2026-08-03 18:49:13.842996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c71bd9c34e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_chef_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_menu_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_plan_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('notifications')
    op.drop_table('earnings')
    op.alter_column('addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_address_city_state', 'addresses', ['city', 'state'], unique=False)
    op.create_index('idx_address_user_type', 'addresses', ['user_id', 'address_type'], unique=False)
    op.create_index(op.f('ix_addresses_address_type'), 'addresses', ['address_type'], unique=False)
    op.create_index(op.f('ix_addresses_city'), 'addresses', ['city'], unique=False)
    op.create_index(op.f('ix_addresses_phone'), 'addresses', ['phone'], unique=False)
    op.create_index(op.f('ix_addresses_pincode'), 'addresses', ['pincode'], unique=False)
    op.create_index(op.f('ix_addresses_state'), 'addresses', ['state'], unique=False)
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.alter_column('cart_items', 'cart_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_cartitem_cart_menu', 'cart_items', ['cart_id', 'menu_id'], unique=False)
    op.create_index('idx_cartitem_cart_special', 'cart_items', ['cart_id', 'special_id'], unique=False)
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_food_type'), 'cart_items', ['food_type'], unique=False)
    op.create_index(op.f('ix_cart_items_menu_id'), 'cart_items', ['menu_id'], unique=False)
    op.create_index(op.f('ix_cart_items_special_id'), 'cart_items', ['special_id'], unique=False)
    op.alter_column('carts', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_cart_user', 'carts', ['user_id'], unique=False)
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=False)
    op.alter_column('chef_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_chefprofile_location', 'chef_profiles', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_chef_profiles_user_id'), 'chef_profiles', ['user_id'], unique=True)
    op.alter_column('menus', 'chef_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_menu_category_available', 'menus', ['category', 'is_available'], unique=False)
    op.create_index('idx_menu_chef_available', 'menus', ['chef_id', 'is_available'], unique=False)
    op.create_index('idx_menu_chef_deleted_available', 'menus', ['chef_id', 'is_deleted', 'is_available'], unique=False)
    op.create_index('idx_menu_foodtype_available', 'menus', ['food_type', 'is_available'], unique=False)
    op.create_index(op.f('ix_menus_category'), 'menus', ['category'], unique=False)
    op.create_index(op.f('ix_menus_chef_id'), 'menus', ['chef_id'], unique=False)
    op.create_index(op.f('ix_menus_food_type'), 'menus', ['food_type'], unique=False)
    op.create_index(op.f('ix_menus_is_available'), 'menus', ['is_available'], unique=False)
    op.create_index(op.f('ix_menus_is_deleted'), 'menus', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_menus_name'), 'menus', ['name'], unique=False)
    op.create_index(op.f('ix_menus_price'), 'menus', ['price'], unique=False)
    op.create_index('idx_orderitem_menu_quantity', 'order_items', ['menu_id', 'quantity'], unique=False)
    op.create_index('idx_orderitem_order_menu', 'order_items', ['order_id', 'menu_id'], unique=False)
    op.create_index('idx_orderitem_order_special', 'order_items', ['order_id', 'special_id'], unique=False)
    op.create_index(op.f('ix_order_items_item_name'), 'order_items', ['item_name'], unique=False)
    op.create_index(op.f('ix_order_items_menu_id'), 'order_items', ['menu_id'], unique=False)
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_items_special_id'), 'order_items', ['special_id'], unique=False)
    op.create_index('idx_order_chef_created', 'orders', ['chef_id', 'created_at'], unique=False)
    op.create_index('idx_order_chef_status', 'orders', ['chef_id', 'status'], unique=False)
    op.create_index('idx_order_created_status', 'orders', ['created_at', 'status'], unique=False)
    op.create_index('idx_order_user_status', 'orders', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_orders_chef_id'), 'orders', ['chef_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_payment_id'), 'orders', ['payment_id'], unique=False)
    op.create_index(op.f('ix_orders_payment_status'), 'orders', ['payment_status'], unique=False)
    op.create_index(op.f('ix_orders_phone'), 'orders', ['phone'], unique=False)
    op.create_index(op.f('ix_orders_refund_status'), 'orders', ['refund_status'], unique=False)
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'chef_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_review_chef_created', 'reviews', ['chef_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_reviews_chef_id'), 'reviews', ['chef_id'], unique=False)
    op.create_index(op.f('ix_reviews_created_at'), 'reviews', ['created_at'], unique=False)
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.alter_column('subscription_plans', 'chef_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index('idx_plan_chef_active', 'subscription_plans', ['chef_id', 'is_active'], unique=False)
    op.create_index('idx_plan_diet_active', 'subscription_plans', ['diet_type', 'is_active'], unique=False)
    op.create_index('idx_plan_goal_active', 'subscription_plans', ['goal', 'is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_chef_id'), 'subscription_plans', ['chef_id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_diet_type'), 'subscription_plans', ['diet_type'], unique=False)
    op.create_index(op.f('ix_subscription_plans_goal'), 'subscription_plans', ['goal'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_title'), 'subscription_plans', ['title'], unique=False)
    op.alter_column('tomorrow_specials', 'chef_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('tomorrow_specials', 'dish_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('tomorrow_specials', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('tomorrow_specials', 'max_plates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index('idx_special_chef_active', 'tomorrow_specials', ['chef_id', 'is_active'], unique=False)
    op.create_index('idx_special_created', 'tomorrow_specials', ['created_at'], unique=False)
    op.create_index('idx_special_food_active', 'tomorrow_specials', ['food_type', 'is_active'], unique=False)
    op.create_index(op.f('ix_tomorrow_specials_chef_id'), 'tomorrow_specials', ['chef_id'], unique=False)
    op.create_index(op.f('ix_tomorrow_specials_created_at'), 'tomorrow_specials', ['created_at'], unique=False)
    op.create_index(op.f('ix_tomorrow_specials_dish_name'), 'tomorrow_specials', ['dish_name'], unique=False)
    op.create_index(op.f('ix_tomorrow_specials_food_type'), 'tomorrow_specials', ['food_type'], unique=False)
    op.create_index(op.f('ix_tomorrow_specials_is_active'), 'tomorrow_specials', ['is_active'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index('idx_user_email_role', 'users', ['email', 'role'], unique=False)
    op.create_index('idx_user_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_is_verified'), 'users', ['is_verified'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_verified'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_role', table_name='users')
    op.drop_index('idx_user_email_role', table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_tomorrow_specials_is_active'), table_name='tomorrow_specials')
    op.drop_index(op.f('ix_tomorrow_specials_food_type'), table_name='tomorrow_specials')
    op.drop_index(op.f('ix_tomorrow_specials_dish_name'), table_name='tomorrow_specials')
    op.drop_index(op.f('ix_tomorrow_specials_created_at'), table_name='tomorrow_specials')
    op.drop_index(op.f('ix_tomorrow_specials_chef_id'), table_name='tomorrow_specials')
    op.drop_index('idx_special_food_active', table_name='tomorrow_specials')
    op.drop_index('idx_special_created', table_name='tomorrow_specials')
    op.drop_index('idx_special_chef_active', table_name='tomorrow_specials')
    op.alter_column('tomorrow_specials', 'max_plates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tomorrow_specials', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('tomorrow_specials', 'dish_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('tomorrow_specials', 'chef_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_subscription_plans_title'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_goal'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_diet_type'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_chef_id'), table_name='subscription_plans')
    op.drop_index('idx_plan_goal_active', table_name='subscription_plans')
    op.drop_index('idx_plan_diet_active', table_name='subscription_plans')
    op.drop_index('idx_plan_chef_active', table_name='subscription_plans')
    op.alter_column('subscription_plans', 'chef_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_created_at'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_chef_id'), table_name='reviews')
    op.drop_index('idx_review_chef_created', table_name='reviews')
    op.alter_column('reviews', 'rating',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('reviews', 'chef_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_refund_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_phone'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_status'), table_name='orders')
    op.drop_index(op.f('ix_orders_payment_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_chef_id'), table_name='orders')
    op.drop_index('idx_order_user_status', table_name='orders')
    op.drop_index('idx_order_created_status', table_name='orders')
    op.drop_index('idx_order_chef_status', table_name='orders')
    op.drop_index('idx_order_chef_created', table_name='orders')
    op.drop_index(op.f('ix_order_items_special_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_menu_id'), table_name='order_items')
    op.drop_index(op.f('ix_order_items_item_name'), table_name='order_items')
    op.drop_index('idx_orderitem_order_special', table_name='order_items')
    op.drop_index('idx_orderitem_order_menu', table_name='order_items')
    op.drop_index('idx_orderitem_menu_quantity', table_name='order_items')
    op.drop_index(op.f('ix_menus_price'), table_name='menus')
    op.drop_index(op.f('ix_menus_name'), table_name='menus')
    op.drop_index(op.f('ix_menus_is_deleted'), table_name='menus')
    op.drop_index(op.f('ix_menus_is_available'), table_name='menus')
    op.drop_index(op.f('ix_menus_food_type'), table_name='menus')
    op.drop_index(op.f('ix_menus_chef_id'), table_name='menus')
    op.drop_index(op.f('ix_menus_category'), table_name='menus')
    op.drop_index('idx_menu_foodtype_available', table_name='menus')
    op.drop_index('idx_menu_chef_deleted_available', table_name='menus')
    op.drop_index('idx_menu_chef_available', table_name='menus')
    op.drop_index('idx_menu_category_available', table_name='menus')
    op.alter_column('menus', 'chef_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_chef_profiles_user_id'), table_name='chef_profiles')
    op.drop_index('idx_chefprofile_location', table_name='chef_profiles')
    op.alter_column('chef_profiles', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.drop_index('idx_cart_user', table_name='carts')
    op.alter_column('carts', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_cart_items_special_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_menu_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_food_type'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_index('idx_cartitem_cart_special', table_name='cart_items')
    op.drop_index('idx_cartitem_cart_menu', table_name='cart_items')
    op.alter_column('cart_items', 'cart_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_state'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_pincode'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_phone'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_city'), table_name='addresses')
    op.drop_index(op.f('ix_addresses_address_type'), table_name='addresses')
    op.drop_index('idx_address_user_type', table_name='addresses')
    op.drop_index('idx_address_city_state', table_name='addresses')
    op.alter_column('addresses', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_table('earnings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chef_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['users.id'], name=op.f('earnings_chef_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('earnings_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('action_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chef_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('menu_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dish_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('meals_per_day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_days', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('delivery_time', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chef_id'], ['users.id'], name=op.f('subscriptions_chef_id_fkey')),
    sa.ForeignKeyConstraint(['menu_id'], ['menus.id'], name=op.f('subscriptions_menu_id_fkey')),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], name=op.f('subscriptions_plan_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('subscriptions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('subscriptions_pkey'))
    )
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_plan_id'), 'subscriptions', ['plan_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_menu_id'), 'subscriptions', ['menu_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_chef_id'), 'subscriptions', ['chef_id'], unique=False)
    # ### end Alembic commands ###
